name: Model Architecture Check

on: [push, pull_request]

jobs:
  check-architecture:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install torch==1.7.0 torchvision==0.8.0 torchsummary==1.5.1
        
    - name: Check model architecture
      run: |
        # python test_model.py
        # dont abort on download error
        set +e
        python test_model.py
        set -e
