name: Model Architecture Check

on: [push, pull_request]

jobs:
  check-model:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r s6/requirements.txt
        
    - name: Check model requirements
      run: |
        python -c "
        import torch
        import sys
        sys.path.append('.')
        from s6.model import Net
        
        model = Net()
        
        # Check total parameters
        total_params = sum(p.numel() for p in model.parameters())
        assert total_params < 20000, f'Model has {total_params} parameters, should be less than 20000'
        
        # Check for batch normalization
        has_bn = any(isinstance(m, torch.nn.BatchNorm2d) for m in model.modules())
        assert has_bn, 'Model should include BatchNormalization'
        
        # Check for dropout
        has_dropout = any(isinstance(m, torch.nn.Dropout2d) for m in model.modules())
        assert has_dropout, 'Model should include Dropout'
        
        print('✓ All architecture checks passed')
        print(f'Total parameters: {total_params}')
        "
